applications/about/urls.py
from django.urls import path, re_path
from . import views

app_name = 'AboutApp'

urlpatterns = [
    path('about/', views.AboutListView.as_view(), name='about')
]

applications/contact/urls.py
from django.urls import path, re_path
from . import views

app_name = 'ContactApp'

urlpatterns = [
    path('contact/', views.Contact.as_view(), name='contact')
]

portafolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('about-app/', include('applications.about.urls')),
    path('work-app/', include('applications.work.urls')),
    path('blog-app/', include('applications.blog.urls')),
    path('contact-app/', include('applications.contact.urls'))
]

applications/about/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Knowledge(models.Model):
    name = models.CharField(max_length = 50, verbose_name="Nombre tus conocimientos")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion") 
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Conocimiento'
        verbose_name_plural = 'Conocimientos'

class Experience(models.Model):
    title = models.CharField(max_length = 50, verbose_name="Titulo", default="Work Experiences")
    name = models.CharField(max_length = 150)
    start_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name="Fecha de inicio de la experiencia")
    end_date = models.DateField(auto_now=False, auto_now_add=False, verbose_name="Fecha final de la experiencia")
    description = RichTextField(verbose_name="Descripcion")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion") 
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Experiencia'
        verbose_name_plural = 'Experiencias'

class Skill(models.Model):
    title = models.CharField(max_length = 25, verbose_name="Titulo", default="My Skills")
    name = models.CharField(max_length = 25, verbose_name="Nombre de la tecnologia")
    porcentage = models.CharField(max_length = 10, verbose_name="Porcentaje")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion") 

    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

class About(models.Model):
    name = models.CharField(max_length = 25, verbose_name="Nombre")
    image_about = models.ImageField(upload_to="static/images/about", height_field=None, width_field=None, max_length=100, verbose_name="Imagen")
    subtitle = models.CharField(max_length = 150, verbose_name="Subtitle")
    description = RichTextField(verbose_name="Descripcion")
    signature = models.ImageField(upload_to="static/images/about", height_field=None, width_field=None, max_length=100, verbose_name="Firma")
    knowledge = models.ManyToManyField(Knowledge, verbose_name="Conocimientos en?")
    experience = models.ManyToManyField(Experience, verbose_name="Experiencia")
    skills = models.ManyToManyField(Skill, verbose_name="Que dominas?")
    is_active = models.BooleanField(verbose_name="La pagina esta activa?", default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion")

    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Sobre mi'

applications/about/views.py
from django.views.generic import ListView
from .models import About
# Create your views here.

class AboutListView(ListView):
    model = About
    template_name = 'about/about.html'
    context_object_name = 'about'

templates/about/about.html
<!-- Banner start -->
{% for item in about %}
{% if item.is_active %}
<section class="section banner-3">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-7">
                <h2 class="text-capitalize mb-5">Sobre Mi</h2>
                <p class="mb-4">{{item.description|safe}}</p>
                <h4>Conocimiento en</h4>
                <ul class="list-unstyled mt-3 about-list">
                    {% for knowledge in item.knowledge.all %}
                    <li>- {{knowledge.name}}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-lg-5">
                <div class="profile mb-5">
                    <img src="{{item.image_about.url}}" alt="" class="img-fluid img-normalizada mb-5 ml-5">
                    <div class="text-center">
                        <h3>{{item.name}}</h3>
                        <p class="lead">{{item.subtitle}}</p>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <!-- Banner End -->

    <!-- About start -->
    <section class="section about">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <h3 class="mb-2">Experiencia</h3>
                </div>
                <div class="col-lg-8">
                    <div class="row">
                        {% for experience in item.experience.all %}
                        <div class="col-lg-6">
                            <div class="about-info mb-5">
                                <span>{{experience.start_date}} - {{experience.end_date}}</span>
                                <h4 class="mb-2 mt-1">{{experience.name}}</h4>
                                <p>{{experience.description|safe}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About End -->

    <!-- Skill Start -->
    <section class="skills">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <h3>Habilidades</h3>
                </div>
                <div class="col-lg-7">
                    <div class="progress-bar-content py-5">
                        {% for skills in item.skills.all %}
                        <div class="progress-label d-flex align-items-center">
                            <div class="progress-title">{{skills.name}}</div>
                            <span class="progress-bar-units ml-auto">{{skills.porcentage}}%</span>
                        </div>
                        <div class="progress">
                            <div class="progress-bar" data-percent="{{skills.porcentage}}"></div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Skill end -->

    <!-- Cta Start -->
    <section class="section-sm pt-0 cta">
        <div class="container">
            <div class="row align-items-center bg-dark p-5">
                <div class="col-lg-8">
                    <h3 class="text-white mb-0">¿Quieres discutir sobre algún proyecto?</h3>
                </div>
                <div class="col-lg-4 text-lg-right mt-lg-0">
                    <a href="{% url 'ContactApp:contact' %}" class="btn btn-white">Contactame</a>
                </div>
            </div>
        </div>
    </section>
    <!-- Cta ENd -->
    {% endif %}
    {% endfor %}
</section>