applications/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'BlogApp'

urlpatterns = [
    path('blog/', views.BlogListView.as_view(), name='blog'),
    path('blog-detail/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail')
]

applications/home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'HomeApp'

urlpatterns = [
    path('', views.HomeListView.as_view(), name='home')
]

portafolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('about-app/', include('applications.about.urls')),
    path('work-app/', include('applications.work.urls')),
    path('blog-app/', include('applications.blog.urls')),
    path('contact-app/', include('applications.contact.urls'))
]

templates/includes/footer.html
<section class="footer">
	<div class="container">
		<div class="row ">
			<div class="col-lg-6">
				<p class="mb-0">Copyrights © 2023. Designed & Developed by <a href="" class="text-white"> Yeferson Correa</a></p>
			</div>
			<div class="col-lg-6">
				<div class="widget footer-widget text-lg-right mt-5 mt-lg-0">
					<ul class="list-inline mb-0">
						<li class="list-inline-item"><a href="https://www.facebook.com/themefisher" target="_blank"><i class="ti-facebook mr-3"></i></a>
						</li>
						<li class="list-inline-item"><a href="https://twitter.com/themefisher" target="_blank"><i class="ti-twitter mr-3"></i></a>
						</li>
						<li class="list-inline-item"><a href="https://github.com/themefisher/" target="_blank"><i class="ti-github mr-3"></i></a></li>
						<li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/" target="_blank"><i class="ti-pinterest mr-3"></i></a></li>
						<li class="list-inline-item"><a href="https://dribbble.com/themefisher/" target="_blank"><i class="ti-dribbble mr-3"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>

templates/includes/header.html
<nav class="navbar navbar-expand-lg  main-nav " id="navbar">
	<div class="container">
		<a class="navbar-brand" href="index.html">
			<img src="images/logo.png" alt="" class="img-fluid">
		</a>

		<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09"
			aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
			<span class="ti-align-justify"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarsExample09">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item  active"><a class="nav-link" href="{% url 'HomeApp:home' %}">Home</a></li>
				<li class="nav-item active"><a class="nav-link" href="{% url 'BlogApp:blog' %}" >Blog</a></li>
			</ul>
		</div>
	</div>
</nav>