applications/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'BlogApp'

urlpatterns = [
    path('blog/', views.BlogListView.as_view(), name='blog'),
    path('blog-detail/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail')
]

portafolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('about-app/', include('applications.about.urls')),
    path('work-app/', include('applications.work.urls')),
    path('blog-app/', include('applications.blog.urls')),
    path('contact-app/', include('applications.contact.urls'))
]

applications/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from .managers import BlogManager, CategoryManager


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 50, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion")
    objects = CategoryManager()
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

class Tags(models.Model):
    name = models.CharField(max_length = 50, verbose_name="Nombre", blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion")

    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Etiqueta'
        verbose_name_plural = 'Etiquetas'

class Comment(models.Model):
    name = models.CharField(max_length = 150, verbose_name="Nombre", blank=True)
    image_comment = models.ImageField(upload_to="static/images/blog/comment", height_field=None, width_field=None, max_length=100, verbose_name="Imagen", blank=True, default="static/images/blog/comment")
    email = models.EmailField(verbose_name="Correo", blank=True)
    comment = models.TextField(verbose_name="Comentario")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion")

    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Comentario'
        verbose_name_plural = 'Comentarios'
        
class Post(models.Model):
    title = models.CharField(max_length = 50, verbose_name="Titulo")
    image_blog = models.ImageField(upload_to="static/images/blog", height_field=None, width_field=None, max_length=100, verbose_name="Imagen")
    content = RichTextField(verbose_name="Contenido")
    view = models.IntegerField(verbose_name="Visitas de la publicacion", default=0)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, verbose_name="Categoria", related_name="Category_Post")
    tags = models.ManyToManyField(Tags, blank=True, verbose_name="Etiquetas")
    comments = models.ManyToManyField(Comment, verbose_name="Comentarios")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion")
    objects = BlogManager()
    
    def __str__(self):
        return self.title

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Publicacion'
        verbose_name_plural = 'Publicaciones'

class Blog(models.Model):
    is_active = models.BooleanField(verbose_name="La pagina esta activa?", default=True)
    post = models.ManyToManyField(Post, verbose_name="Publicaciones")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion")

    def __str__(self):
        return f"Blog"

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

applications/blog/views.py
from django.views.generic import ListView, DetailView
from django.db.models import Count
from . models import Blog, Post, Tags, Category
# Create your views here.


class BlogListView(ListView):
    model = Post
    template_name = "blog/blog.html"
    ordering = 'id'
    paginate_by = 6
    context_object_name = 'post'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['popular'] = Post.objects.get_popular_posts()
        context['tags'] = Tags.objects.all()
        context['categorycount'] = Category.objects.catidad_por_categoria()
        return context

class BlogDetailView(DetailView):
    model = Post
    template_name = "blog/blogDetail.html"
    context_object_name = 'post'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.view += 1
        obj.save()
        return obj

templates/blog/blog.html
{% extends "base.html" %}

{% block title %}Blog{% endblock title %}

{% block content %}
{% include "includes/header.html" %}
<section class="page-title section pb-0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center">
                    <h1 class="text-capitalize mb-0 text-lg">Blog</h1>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section blog-post">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    {% for item in post %}
                    <div class="col-lg-4 col-md-6">
                        <div class="post mb-5">
                            <a class="image-content" href="{% url 'BlogApp:blog-detail' item.id %}">
                                <img src="{{item.image_blog.url}}" alt="" class="img-fluid">
                            </a>

                            <div class="post-content">
                                <span class="date text-uppercase text-sm">{{item.created}}</span>
                                <a href="{% url 'BlogApp:blog-detail' item.id %}">
                                    <h4>{{item.title}}</h4>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% include "blog/sidebar.html" with post=popular tags=tags categorycount=categorycount %}
        </div>
        <div class="row">
            <div class="col-lg-12">
                {% if is_paginated %}
                <nav class="pagination">
                    <ul class="list-inline d-block mx-auto">
                        {% if page_obj.has_previous %}
                        <li class="list-inline-item">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %}
                        <li class="active list-inline-item">
                            <a href="#"><span>{{pagina}}</span></a>
                        </li>
                        {% else %}
                        <li class="active list-inline-item">
                            <a href="?page={{pagina}}">
                                <span>{{pagina}}</span>
                            </a>
                        </li>
                        {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="list-inline-item">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% include "includes/footer.html" %}
{% endblock content %}

templates/blog/blogDetail.html
{% extends "base.html" %}

{% block title %}

{% endblock title %}

{% block content %}
{% include "includes/header.html" %}
<section class="page-title section pb-0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center">
                    <h1 class="text-capitalize mb-0 text-lg">Blog</h1>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section blog-post">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <article class="single-post text-center">
                    <img src="{{post.image_blog.url}}" alt="" class="img-fluid">
                    <div class="single-post-content mt-4">
                        <div class="post-meta mb-4">
                            <span class="text-black">Tags :</span>
                            {% for item in post.tags.all %}
                            <span>{{post.name}}</span>
                            {% endfor %}
                            <span class="ml-3">-</span>
                            <span class="date">{{post.created}}</span>
                        </div>
                        <h3>{{post.title}}</h3>

                        <p>{{post.content}}</p>

                        <div class="share mt-4">
                            <ul class="list-inline">
                                <li class="mb-3">Share Now :</li>
                                <li class="list-inline-item"><a href="#"><i class="ti-facebook mr-2"></i> Facebook</a>
                                </li>
                                <li class="list-inline-item"><a href="#"><i class="ti-twitter mr-2"></i> Twitter</a>
                                </li>
                                <li class="list-inline-item"><a href="#"><i class="ti-linkedin mr-2"></i> Linkedin</a>
                                </li>
                                <li class="list-inline-item"><a href="#"><i class="ti-pinterest mr-2"></i> Pinterest</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </article>

                <!--Comentarios-->
                <div class="comments bg-secondary p-4 mt-5">
                    <h4 class="mb-4">Comments</h4>
                    <div class="latest-comments">
                        {% for comment in post.comments.all %}
                        <ul class="list-unstyled">
                            <li>
                                <div class="media comments-box mb-45">
                                    <img src="{{comment.image_comment.url}}" alt="" class="img-fluid mr-3">
                                    <div class="comments-text media-body">
                                        <h5>{{comment.name}}</h5>
                                        <p>{{comment.comment}}</p>
                                        <a href="#" class="text-sm text-muted">Reply</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        {% endfor %}
                    </div>
                </div>

                <!--Formulario-->
                <div class="comment-form bg-secondary p-4 mt-5">
                    <h4 class="mb-4">Leave a comment</h4>
                    <form action="#" class="comment-form">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Your name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Your Email">
                        </div>
                        <div class="form-group">
                            <textarea name="msg" id="msg" cols="30" rows="4" class="form-control"
                                placeholder="Your Comment"></textarea>
                        </div>

                        <a href="#" class="btn btn-main">Post Comment</a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% include "includes/footer.html" %}
{% endblock content %}

templates/blog/sidebar.html
<div class="col-lg-4">
    <div class="sidebar-widget mt-5 mt-lg-0">
        <div class="widget mb-5 follow">
            <h4 class="mb-4 widget-title">Follow us</h4>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="ti-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="ti-github"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="ti-pinterest"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="ti-dribbble"></i></a></li>
            </ul>
        </div>

        <div class="widget mb-5">
            <h4 class="mb-4 widget-title">Popular Posts</h4>
            <ul class="list-unstyled">
                {% for item in post %}
                <li class="d-flex mb-4">
                    <img src="{{item.image_blog.url}}" alt="" width="120" class="img-fluid mr-3">
                    <div class="post-body">
                        <span class="text-capitalize">By Admin</span>
                        <a href="#">
                            <h5>{{item.title}}</h5>
                        </a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="widget category mb-5">
            <h4 class="mb-4 widget-title">Categories</h4>
            <ul class="list-unstyled">
                {% for item in categorycount %}
                <li class="d-flex justify-content-between align-items-center">
                    <a href="#">{{item.name}}</a>
                    <span class="cat-count">{{item.num_post}}</span>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="widget mb-5 tags">
            <h4 class="mb-4 widget-title">Tags</h4>
            <ul class="list-inline">
                {% for item in tags %}
                <li class="list-inline-item"><a href="#">{{item.name}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>