applications/work/urls.py
from django.urls import path, re_path
from . import views

app_name = 'WorkApp'

urlpatterns = [
    path('work/', views.WorkListView.as_view(), name='work'),
    path('detail-work/<int:pk>', views.WorkDetailView.as_view(), name='detail')
]

portafolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('about-app/', include('applications.about.urls')),
    path('work-app/', include('applications.work.urls')),
    path('blog-app/', include('applications.blog.urls')),
    path('contact-app/', include('applications.contact.urls'))
]

applications/work/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 50, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion") 
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

class Project(models.Model):
    name = models.CharField(max_length = 25, verbose_name="Nombre")
    category = models.ManyToManyField(Category, verbose_name="Categoria")
    description = RichTextField(verbose_name="Descripcion")
    image_project = models.ImageField(upload_to="static/images/portafolio", height_field=None, width_field=None, max_length=100, verbose_name="Imagen")
    customer = models.CharField(max_length = 25, verbose_name="Nombre al que se realizo el proyecto", blank=True)
    url = models.TextField(verbose_name="Url de git")
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion")
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'

class WorkPage(models.Model):
    title = models.CharField(max_length = 150, verbose_name="Titulo")
    project = models.ManyToManyField(Project, verbose_name="Proyecto")
    is_active = models.BooleanField(verbose_name="La pagina esta activa?", default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name= "Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualizacion") 

    def __str__(self):
        return self.title

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Portafolio'
        verbose_name_plural = 'Portafolios'

applications/work/views.py
from django.views.generic import ListView, DetailView
from .models import Project, Category
# Create your views here.

class WorkListView(ListView):
    model = Project
    template_name = "work/work.html"
    ordering = 'id'
    paginate_by = 2
    context_object_name = 'work'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = Project.objects.all()
        context['category'] = Category.objects.all()
        return context

class WorkDetailView(DetailView):
    model = Project
    template_name = "work/workDetail.html"
    context_object_name = 'project'

templates/work/homeWork.html
{% block content %}
<section class="portfolio service-home border-top">
    <div class="container py-5">
        <div class="row">
            <div class="col-10">
                <h2 class="mb-5">Portafolio</h2>
                <p class="mb-5">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, totam ipsa quia hic odit a sit laboriosam voluptatem in, blanditiis.
				</p>
                <div class="btn-group btn-group-toggle " data-toggle="buttons">
                    <label class="btn active ">
                        <input type="radio" name="shuffle-filter" value="all" checked="checked" />All Projects
                    </label>
                    {% for item in category %}
                    <label class="btn">
                        <input type="radio" name="shuffle-filter" value="{{item.name}}" />{{item.name}}
                    </label>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row shuffle-wrapper portfolio-gallery py-5">
            {% for item in workhome %}
            {% for category in item.category.all %}
            <div class="col-lg-4 col-6 mb-5 shuffle-item" data-groups="[&quot;{{category.name}}&quot;]">
                <div class="position-relative inner-box">
                    <div class="image position-relative ">
                        <img src="{{item.image_project.url}}" alt="portfolio-image" class="img-fluid w-100 d-block">
                        <div class="overlay-box">
                            <div class="overlay-inner">
                                <a class="overlay-content" href="{% url 'WorkApp:detail' item.id %}">
                                    <h5 class="mb-0">{{item.name}}</h5>
                                    <p>{{category.name}}</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-2">
                <a href="{% url 'WorkApp:work' %}" class="btn btn-blue">Ver mas</a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/work/work.html
{% extends "base.html" %}

{% block title %}Portafolio{% endblock title %}

{% block content %}
{% include "includes/header.html" %}
<section class="section banner pb-lg-0 page-title">
    <div class="container">
        <h1 class="text-capitalize mb-5 text-lg text-center">Portafolio</h1>
    </div>
</section>
<section class=" portfolio ">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-lg-7">
                <div class="btn-group btn-group-toggle " data-toggle="buttons">
                    <label class="btn active ">
                        <input type="radio" name="shuffle-filter" value="all" checked="checked" />All Projects
                    </label>
                    {% for item in category %}
                    <label class="btn">
                        <input type="radio" name="shuffle-filter" value="{{item.name}}" />{{item.name}}
                    </label>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row shuffle-wrapper portfolio-gallery">
            {% for item in project %}
            {% for category in item.category.all %}
            <div class="col-lg-4 col-6 mb-4 shuffle-item" data-groups="[&quot;{{category.name}}&quot;]">
                <div class="position-relative inner-box">
                    <div class="image position-relative ">
                        <img src="{{item.image_project.url}}" alt="portfolio-image" class="img-fluid w-100 d-block">
                        <div class="overlay-box">
                            <div class="overlay-inner">
                                <a class="overlay-content" href="{% url 'WorkApp:detail' item.id %}">
                                    <h5 class="mb-0 ">{{item.name}}</h5>
                                    <p>{{category.name}}</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endfor %}
        </div>
    </div>
</section>
{% include "includes/footer.html" %}
{% endblock content %}

templates/work/workDetail.html
{% extends 'base.html' %}


{% block title %}Detalle proyecto{% endblock title %}

{% block content %}
{% include "includes/header.html" %}
<section class="page-title section pb-0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center">
                    <h1 class="text-capitalize mb-0 text-lg">Proyecto {{project.name}}</h1>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="section portfolio-single">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <img src="{{project.image_project.url}}" alt="" class="img-fluid w-100">
            </div>

            <div class="col-lg-6">
                <div class="project-info">
                    <h3 class="mb-4">{{project.name}}</h3>
                    <p>{{project.description}}</p>

                    <div class="row mt-4">
                        <div class="col-lg-6">
                            <div class="info">
                                <h5 class="mb-0">Client</h5>
                                <p>{{project.customer}}</p>
                            </div>

                            <div class="info">
                                <h5 class="mb-0">Date</h5>
                                <p>{{project.created}}</p>
                            </div>
                            <div class="mt-4">
                                <a href="{{project.url}}" class="btn btn-main btn-small">Ver proyecto</a>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="info">
                                <h5 class="mb-0">Category</h5>
                                {% for item in project.category.all %}
                                <p>{{item.name}}</p>
                                {% endfor %}
                            </div>
                            <div class="info">
                                <h5>Share</h5>
                                <a href="#"><i class="ti-facebook"></i></a>
                                <a href="#"><i class="ti-twitter"></i></a>
                                <a href="#"><i class="ti-pinterest"></i></a>
                                <a href="#"><i class="ti-dribbble"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% include "includes/footer.html" %}
{% endblock content %}